In [1]:
import pandas as pd

sellers = pd.read_csv('../data/raw/olist_sellers_dataset.csv', dtype={'seller_zip_code_prefix': str})
print(sellers.shape)
sellers.head()

(3095, 4)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [2]:
# construire et contrôler dim_vendeur

dim_vendeur = sellers[['seller_id', 'seller_city', 'seller_zip_code_prefix']].copy()
dim_vendeur.columns = ['seller_id', 'ville', 'code_postal_prefixe']
assert len(dim_vendeur) == 3095
assert dim_vendeur['seller_id'].is_unique
assert dim_vendeur['code_postal_prefixe'].str.len().eq(5).all()
assert dim_vendeur.isna().sum().sum() == 0
print("Contrôles DimVendeur OK")
dim_vendeur.head()

Contrôles DimVendeur OK

                          seller_id              ville code_postal_prefixe
0  3442f8959a84dea7ee197c632cb2df15           campinas               13023
1  d1b65fc7debc3361ea86b5f14c68d2e2         mogi guacu               13844
2  ce3ad9de960102d0677a81f5d0bb7b2d     rio de janeiro               20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3          sao paulo               04195
4  51a04a8a6bdcb23deccc82b0b80742cf  braganca paulista               12914